# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: lukas.boettcher@sick.de
author_name: Lukas Boettcher
has_binder: false
has_settings: false
kind: server
labextension_name: disk-usage
project_short_description: A JupyterLab extension to monitor disk usage.
python_name: disk_usage
repository: https://github.com/lukasboettcher/jupyterlab-disk-usage
test: false

